parameters:
  serviceConnection: ''

jobs:
- job: Keyvault
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: AzureKeyVault@1
    displayName: 'Get Secrets from Keyvault'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      keyVaultName: $(keyvaultName)
      secretsFilter: 'aks-mgmt-sp-id,aks-mgmt-sp-secret'      

  - script: |
      echo "##vso[task.setvariable variable=aksServicePrincipalId;isOutput=true]$(aks-mgmt-sp-id)"
      echo "##vso[task.setvariable variable=aksServicePrincipalSecret;isOutput=true]$(aks-mgmt-sp-secret)"
    displayName: 'Translate Keyvault Variables'
    name: exportKeyvault
