variables:
  environment: 'hmctsdemo'
  aksResourceGroup: 'k8-$(environment)'
  subnetResourceGroup: 'core-infra-$(environment)'
  subnetName: 'aks-subnet'
  vnetName: 'core-infra-vnet-$(environment)'
  location: 'uksouth'
  clusterName: 'k8-cluster-$(environment)'
  nodeCount: '10'
  nodeDiskSize: '100'
  vmSize: 'Standard_D4s_v3'
  kubernetesVersion: '1.11.4'
  keyvaultName: 'k8-vault-$(environment)'
  kubectlConnectionType: 'Azure Resource Manager'

jobs:
- template: ../jobs/vault-read.yml
  parameters:
    serviceConnection: azurerm-$(environment)
    
- template: ../jobs/k8-deploy.yml
  parameters:
    serviceConnection: azurerm-$(environment)
