name: HMCTSDemo K8 Infrastructure Deployment Pipeline
trigger: none
variables:
  environment: 'hmctsdemo'
  aksResourceGroup: 'k8-${environment}'
  aksClusterName: 'k8-cluster-${environment}'
  keyvaultName: 'k8-vault-${environment}'
  serviceConnection: 'azurerm-${environment}'
  aksParametersFile: '${environment}.json'

jobs:
- job: KeyVault
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: ../steps/keyvault-read.yaml
    parameters:
      serviceConnection: $(serviceConnection)
      keyvaultName: $(keyvaultName)

- job: DeployK8
  dependsOn: KeyVault
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    aksServicePrincipalId: $[dependencies.Keyvault.outputs['exportKeyvault.aksServicePrincipalId']]
    aksServicePrincipalSecret: $[dependencies.Keyvault.outputs['exportKeyvault.aksServicePrincipalSecret']]
  steps:
  - template: ../tasks/helm-installer.yaml
  - template: ../steps/k8-deploy.yaml
    parameters:
      serviceConnection: $(serviceConnection)
      aksResourceGroup: $(aksResourceGroup)
      aksClusterName: $(aksClusterName)
      aksParametersFile: $(aksParametersFile)

- job: InstallKured
  dependsOn: DeployK8
  condition: succeeded()
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: ../steps/helm-configure.yaml
    parameters:
      serviceConnection: $(serviceConnection)
      aksResourceGroup: $(aksResourceGroup)
      aksClusterName: $(aksClusterName)
  - template: ../steps/kured-install.yaml
    parameters:
      serviceConnection: $(serviceConnection)
      aksResourceGroup: $(aksResourceGroup)
      aksClusterName: $(aksClusterName)
