parameters:
  serviceConnection: ''
  aksResourceGroup: ''
  aksClusterName: ''

steps:
- template: ../steps/helm-install.yaml

- task: HelmDeploy@0
  displayName: 'Initialise Helm Client'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: ${{ parameters.serviceConnection }}
    azureResourceGroup: ${{ parameters.aksResourceGroup }}
    kubernetesCluster: ${{ parameters.aksClusterName }}
    kubernetesServiceEndpoint: ''
    command: 'init'
    arguments: '--client-only'
