parameters:
  serviceConnection: ''
  aksResourceGroup: ''
  aksClusterName: ''
  ingressDNSName: ''

steps:
- task: HelmDeploy@0
  displayName: 'Install Nginx Ingress Controller'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: ${{ parameters.serviceConnection }}
    azureResourceGroup: ${{ parameters.aksResourceGroup }}
    kubernetesCluster: ${{ parameters.aksClusterName }}
    command: 'install'
    chartType: 'Name'
    chartName: 'stable/nginx-ingress'
    arguments: '--namespace kube-system --set controller.replicaCount=2'

- task: Kubernetes@1
  displayName: 'Get Public IP of Nginx Ingress Controller'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: ${{ parameters.serviceConnection }}
    azureResourceGroup: ${{ parameters.aksResourceGroup }}
    kubernetesCluster: ${{ parameters.aksClusterName }}
    command: 'get'
    arguments: 'service -l app=nginx-ingress --namespace kube-system'
    outputFormat: 'json'
    
- script: |
    echo "##vso[task.setvariable variable=PUBLIC_IP;isOutput=true] invalid"
    echo "##vso[task.setvariable variable=DNS_NAME;isOutput=true]$(parameters.ingressDNSName)"
    
- task: ShellScript@2
  displayName: 'Update DNS Record with IP of Nginx Ingress Controller'
  inputs:
    scriptPath: scripts/ingress-dns-update.sh
